export const ratelist = {
  XRAY_rate_List: [
    {
      investigations: "Abdomen",
      rate: "500",
      film_count: "1",
    },
    {
      investigations: "ARM AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "ANKLE AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "CHEST PA VIEW",
      rate: "400",
      film_count: "1",
    },
    {
      investigations: "CERVICAL SPINE AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "ELBOW AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "FOOT AP/OBLIQUE",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "FOREARM AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "HAND AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "IVP",
      rate: "3000",
      film_count: "1",
    },
    {
      investigations: "KNEE AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "KUB",
      rate: "600",
      film_count: "1",
    },
    {
      investigations: "LEG AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "LUMBAR SPINE AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "MANDIBLE",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "RGU",
      rate: "3000",
      film_count: "1",
    },
    {
      investigations: "MCU",
      rate: "3000",
      film_count: "1",
    },
    {
      investigations: "RGU AND MCU",
      rate: "5000",
      film_count: "1",
    },
    {
      investigations: "NECK",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "ORBIT",
      rate: "600",
      film_count: "1",
    },
    {
      investigations: "PELVIS",
      rate: "600",
      film_count: "1",
    },
    {
      investigations: "PELVIS WITH SINGLE HIP",
      rate: "600",
      film_count: "1",
    },
    {
      investigations: "PELVIS WITH BOTH HIP",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "PNS",
      rate: "700",
      film_count: "1",
    },
    {
      investigations: "SKULL",
      rate: "700",
      film_count: "1",
    },
    {
      investigations: "SHOULDER AP/OBLIQUE",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "THIGH AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "THORACIC SPINE AP/LAT",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "METACARPAL/ FINGER AP/OBLIQUE",
      rate: "800",
      film_count: "1",
    },
    {
      investigations: "WRIST AP/LATERAL",
      rate: "800",
      film_count: "1",
    },
  ],
  CT_Scan_rate_List: [
    {
      Sr_No: "1",
      investigations: "BRAIN PLAIN",
      rate: "2500",
      film_count: "1",
    },
    {
      Sr_No: "2",
      investigations: "BRAIN WITH CONTRAST",
      rate: "3500",
      film_count: "2",
    },
    {
      Sr_No: "3",
      investigations: "CONTRAST CHARGES",
      rate: "1000",
      film_count: "0",
    },
    {
      Sr_No: "4",
      investigations: "ABDOMEN PLAIN",
      rate: "5000",
      film_count: "2",
    },
    {
      Sr_No: "5",
      investigations: "ABDOMEN WITH PELVIS CONTRAST",
      rate: "7000",
      film_count: "3",
    },
    {
      Sr_No: "7",
      investigations: "PNS WITH CONTRAST",
      rate: "4500",
      film_count: "4",
    },
    {
      Sr_No: "8",
      investigations: "NECK PLAIN",
      rate: "3500",
      film_count: "3",
    },
    {
      Sr_No: "9",
      investigations: "NECK WITH CONTRAST",
      rate: "4500",
      film_count: "4",
    },
    {
      investigations: "CHEST PLAIN",
      rate: "3500",
      film_count: "3",
    },
    {
      investigations: "CHEST CONTRAST",
      rate: "4500",
      film_count: "4",
    },
    {
      investigations: "TEMPORAL BONE PLAIN",
      rate: "5000",
      film_count: "2",
    },
    {
      investigations: "TEMPORAL BONE WITH CONTRAST",
      rate: "6500",
      film_count: "3",
    },
    {
      investigations: "PELVIS PLAIN",
      rate: "4500",
      film_count: "2/3",
    },
    {
      investigations: "PELVIS WITH CONTRAST",
      rate: "5500",
      film_count: "4",
    },
    {
      investigations: "PELVIS WITH HIP JOINT PLAIN",
      rate: "4500",
      film_count: "3",
    },
    {
      investigations: "UROGRAPHY /KUB PLAIN",
      rate: "6000",
      film_count: "2",
    },
    {
      investigations: "UROGRAPHY /KUB CONTRAST",
      rate: "7000",
      film_count: "3",
    },
    {
      investigations: "FACE WITH 3D RECONSTRUCTION",
      rate: "5000",
      film_count: "3",
    },
    {
      investigations: "ANGIOGRAPHY ANY REGION ",
      rate: "12000",
      film_count: "3",
    },
    {
      investigations: "JOINTS WITH 3D RECONSTRUCTION",
      rate: "4500",
      film_count: "3",
    },
    {
      investigations: "CERVICAL SPINE",
      rate: "5000",
      film_count: "2",
    },
    {
      investigations: "THORACIC/DORSAL SPINE",
      rate: "5000",
      film_count: "2",
    },
    {
      investigations: "LUMBAR SPINE",
      rate: "5000",
      film_count: "2",
    },
    {
      investigations: "EMERGENCY CHARGES (after 9 PM)",
      rate: "1000",
      film_count: "0",
    },
    {
      investigations: "CT GUIDED BIOPSY OF LUNGS MASS",
      rate: "8000",
      film_count: "0",
    },
    {
      investigations: "CT GUIDED BIOPSY OF ABDOMEN MASS",
      rate: "8000",
      film_count: "0",
    },
  ],
  USG_rate_List: [
    { investigations: "ABDOMEN", rate: "1000" },
    { investigations: "PELVIS", rate: "900" },
    { investigations: "3 D PELVIS", rate: "2000" },
    { investigations: "KUB", rate: "900" },
    { investigations: "OBSTETRIC ROUTINE", rate: "1200" },
    { investigations: "ANOMALY / NT SCAN", rate: "1700" },
    { investigations: "NECK / THYROID", rate: "1200" },
    { investigations: "BREAST - SINGLE", rate: "800" },
    { investigations: "BREAST - BOTH SIDE", rate: "1200" },
    {
      investigations: "LOCAL AREA / SOFT TISSUE",
      rate: "900",
    },
    { investigations: "SCROTUM", rate: "1300" },
    { investigations: "INGUINAL REGION", rate: "1000" },
    { investigations: "OVULATION STUDY", rate: "1000" },
    { investigations: "4 D USG", rate: "5500" },
    { investigations: "FETAL ECHO", rate: "2000" },
    { investigations: "JOINT", rate: "1500" },
    { investigations: "NEUROSONOGRAM", rate: "1300" },
    { investigations: "THORAX", rate: "1200" },
    { investigations: "OBSTETRIC DOPPLER", rate: "1500" },
    { investigations: "CAROTID DOPPLER", rate: "1500" },
    { investigations: "RENAL DOPPLER", rate: "1800" },
    { investigations: "SCROTAL DOPPLER", rate: "1500" },
    { investigations: "PORTAL DOPPLER", rate: "1500" },
    { investigations: "PENILE DOPPLER", rate: "1500" },
    {
      investigations: "ARTERIAL DOPPLER- SINGLE LIMB",
      rate: "1500",
    },
    {
      investigations: "ARTERIAL DOPPLER - BOTH LIMBS",
      rate: "3000",
    },
    {
      investigations: "VENOUS DOPPLER - SINGLE LIMB",
      rate: "1500",
    },
    {
      investigations: "VENOUS DOPPLER - BOTH LIMBS",
      rate: "3000",
    },
    { investigations: "USG GUIDED FNAC", rate: "2500" },
    { investigations: "USG GUIDED BIOPSY", rate: "6000" },
    { investigations: "USG GUIDED TAPPING", rate: "1500" },
    {
      investigations: "USG GUIDED PIG TAIL INSERTION",
      rate: "10000",
    },
    { investigations: "EMERGENCY CHARGES", rate: "1000" },
  ],
};
